create table "public"."capybara_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."capybara_table" enable row level security;

CREATE UNIQUE INDEX capybara_table_pkey ON public.capybara_table USING btree (id);

alter table "public"."capybara_table" add constraint "capybara_table_pkey" PRIMARY KEY using index "capybara_table_pkey";

grant delete on table "public"."capybara_table" to "anon";

grant insert on table "public"."capybara_table" to "anon";

grant references on table "public"."capybara_table" to "anon";

grant select on table "public"."capybara_table" to "anon";

grant trigger on table "public"."capybara_table" to "anon";

grant truncate on table "public"."capybara_table" to "anon";

grant update on table "public"."capybara_table" to "anon";

grant delete on table "public"."capybara_table" to "authenticated";

grant insert on table "public"."capybara_table" to "authenticated";

grant references on table "public"."capybara_table" to "authenticated";

grant select on table "public"."capybara_table" to "authenticated";

grant trigger on table "public"."capybara_table" to "authenticated";

grant truncate on table "public"."capybara_table" to "authenticated";

grant update on table "public"."capybara_table" to "authenticated";

grant delete on table "public"."capybara_table" to "service_role";

grant insert on table "public"."capybara_table" to "service_role";

grant references on table "public"."capybara_table" to "service_role";

grant select on table "public"."capybara_table" to "service_role";

grant trigger on table "public"."capybara_table" to "service_role";

grant truncate on table "public"."capybara_table" to "service_role";

grant update on table "public"."capybara_table" to "service_role";


